/**
 * zudojs-cli — Versions of the @zudojs/* packages this CLI build targets.
 *
 * GENERATED by scripts/generateZudojsVersions.mjs from the package.json of
 * every workspace package.
 * Do not edit by hand; run `node scripts/generateZudojsVersions.mjs`.
 */

export const ZUDOJS_PACKAGE_VERSIONS: Readonly<Record<string, string>> =
  Object.freeze({
  "@zudojs/adapters": "1.2.0",
  "@zudojs/api": "1.1.1",
  "@zudojs/auth": "1.2.1",
  "@zudojs/auth-oauth": "1.2.1",
  "@zudojs/cache": "1.1.1",
  "@zudojs/config": "1.2.0",
  "@zudojs/constants": "1.1.1",
  "@zudojs/container": "1.1.2",
  "@zudojs/core": "1.2.1",
  "@zudojs/cqrs": "1.1.1",
  "@zudojs/crypto": "1.3.0",
  "@zudojs/database": "1.2.1",
  "@zudojs/docs": "1.0.3",
  "@zudojs/errors": "1.2.0",
  "@zudojs/events": "1.2.0",
  "@zudojs/feature-flags": "1.3.0",
  "@zudojs/http": "1.3.0",
  "@zudojs/lifecycle": "1.2.0",
  "@zudojs/logger": "1.3.0",
  "@zudojs/messaging": "1.1.0",
  "@zudojs/middleware": "1.0.3",
  "@zudojs/observability": "1.1.1",
  "@zudojs/openapi": "1.4.0",
  "@zudojs/permissions": "1.3.0",
  "@zudojs/plugins": "1.2.1",
  "@zudojs/queue": "1.3.0",
  "@zudojs/rpc": "1.3.0",
  "@zudojs/runtime": "1.2.1",
  "@zudojs/scheduler": "1.1.2",
  "@zudojs/schema": "1.1.1",
  "@zudojs/security": "1.2.0",
  "@zudojs/serialization": "1.1.1",
  "@zudojs/storage": "1.1.2",
  "@zudojs/tenancy": "1.2.1",
  "@zudojs/testing": "1.1.2",
  "@zudojs/transactions": "1.1.2",
  "@zudojs/types": "1.1.1",
  "@zudojs/validation": "1.0.3",
  });
