/**
 * Page templates for /learn: one page per lesson plus the course index.
 * Shares the docs shell (header, sidebar, TOC, footer) so docs.js and
 * components.js work unchanged.
 */

import { escapeAttr, escapeHtml } from "./source.mjs";

function tierBadge(course, tier, extra = "") {
  const t = course.tiers && course.tiers[tier];
  if (!t) return "";
  return `<span class="lx-tier lx-tier-${tier}${extra}" title="${escapeAttr(t.label + ": " + t.summary)}">${escapeHtml(t.label)}</span>`;
}

function head({ title, description, path, keywords }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="theme-color" content="#1A1A2E">
  <title>${escapeHtml(title)}</title>
  <link rel="alternate" type="text/markdown" href="${path === "/learn" ? "/learn/index" : path}.md" title="Markdown version">
  <meta name="description" content="${escapeAttr(description)}">
  <!-- seo:start -->
  <!-- seo:end -->
  <meta name="keywords" content="${escapeAttr(keywords || "zudo, learn, javascript, typescript, node.js, backend, tutorial")}">
  <meta name="author" content="Oyinlola Tech">

  <link rel="icon" type="image/svg+xml" href="/assets/zudo-favicon.svg">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png">

  <link rel="preload" href="/assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="/css/site.css">
  <link rel="stylesheet" href="/css/docs.css">
  <link rel="stylesheet" href="/css/playground.css">
  <link rel="stylesheet" href="/css/learn.css">
  <link rel="stylesheet" href="/css/tailwind.css">
</head>
<body class="bg-zudo-white text-zudo-black">

  <!-- NAVBAR -->
  <div id="zudo-nav"></div>
`;
}

function sidebar(course, lessons, activeSlug) {
  let html = `    <aside class="doc-sidebar lx-sidebar" id="docSidebar" aria-label="Learn">\n`;
  html += `      <a href="/learn" class="sidebar-item${activeSlug === null ? " sidebar-item-active" : ""}">Course overview</a>\n`;
  for (const part of course.parts) {
    if (!lessons.some((l) => l.partId === part.id)) continue;
    html += `      <div class="sidebar-section mt-4">${escapeHtml(part.title)}</div>\n`;
    for (const l of lessons.filter((x) => x.partId === part.id)) {
      const active = l.slug === activeSlug ? " sidebar-item-active" : "";
      html += `      <a href="/learn/${l.slug}" class="sidebar-item lx-side-item${active}" data-lesson="${l.slug}"><span class="lx-side-num">${l.number}</span>${escapeHtml(l.meta.title)}</a>\n`;
    }
  }
  html += `      <div class="sidebar-section mt-4">Reference</div>\n`;
  html += `      <a href="/docs/getting-started" class="sidebar-item">Docs</a>\n`;
  html += `      <a href="/docs/packages" class="sidebar-item">All packages</a>\n`;
  html += `    </aside>\n`;
  return html;
}

function foot() {
  return `
  <script src="/js/docs.js" defer></script>
  <script src="/js/components.js" defer></script>
  <script src="/js/playground.js" defer></script>
  <script src="/js/learn.js" defer></script>

  <div id="zudo-footer"></div>
</body>
</html>
`;
}

export function lessonPage({ course, lessons, lesson, bodyHtml, toc }) {
  const i = lessons.indexOf(lesson);
  const prev = lessons[i - 1];
  const next = lessons[i + 1];
  const m = lesson.meta;
  const path = `/learn/${lesson.slug}`;
  const title = `${m.title} — Learn ZudoJS`;
  let html = head({ title, description: m.description, path, keywords: m.keywords });
  html += `
  <!-- ==================== LAYOUT ==================== -->
  <div class="flex max-w-screen-2xl mx-auto">

    <!-- learn:sidebar (generated by scripts/site-learn.mjs) -->
${sidebar(course, lessons, lesson.slug)}
    <main id="main" class="flex-1 min-w-0 px-8 py-10 max-w-4xl lx-main" data-lesson="${lesson.slug}">
      <div class="text-sm mb-6">
        <a href="/learn" class="hover:text-zudo-blue">Learn</a>
        <span class="mx-2 text-black/60">/</span>
        <span class="text-black/60">${escapeHtml(lesson.part)}</span>
      </div>

      <header class="lx-hero">
        <div class="lx-hero-tag">LESSON ${lesson.number} OF ${lessons.length}</div>
        <p class="lx-hero-part">${escapeHtml(lesson.part)} ${tierBadge(course, lesson.tier)}</p>
        <h1>${escapeHtml(m.title)}</h1>
        <p class="lx-hero-lead">${escapeHtml(m.description)}</p>
        <ul class="lx-hero-meta">
          <li><strong>${escapeHtml(m.minutes || "15")} min</strong> to read and try</li>
          ${m.youNeed ? `<li><strong>You need:</strong> ${escapeHtml(m.youNeed)}</li>` : ""}
          ${m.youBuild ? `<li><strong>You build:</strong> ${escapeHtml(m.youBuild)}</li>` : ""}
        </ul>
      </header>

      <div class="lx-body">
${bodyHtml.trim()}
      </div>

      <div class="lx-finish">
        <button type="button" class="lx-done" data-lesson="${lesson.slug}">Mark this lesson as done</button>
      </div>

      <nav class="lx-pager" aria-label="Lessons">
        ${prev ? `<a href="/learn/${prev.slug}" class="lx-pager-link"><span>← Lesson ${prev.number}</span>${escapeHtml(prev.meta.title)}</a>` : `<a href="/learn" class="lx-pager-link"><span>← Course</span>Overview</a>`}
        ${next ? `<a href="/learn/${next.slug}" class="lx-pager-link lx-pager-next"><span>Lesson ${next.number} →</span>${escapeHtml(next.meta.title)}</a>` : `<a href="/docs/getting-started" class="lx-pager-link lx-pager-next"><span>Keep going →</span>The docs</a>`}
      </nav>
    </main>

    <aside class="doc-toc" aria-label="On this page">
      <div class="p-4 text-xs font-bold uppercase text-black/60 tracking-wider">On this page</div>
${toc.map((h) => `      <a href="#${h.id}" class="toc-link">${escapeHtml(h.text)}</a>`).join("\n")}
    </aside>

  </div>
`;
  return html + foot();
}

export function indexPage({ course, lessons }) {
  const m = course.index;
  let html = head({ title: m.title, description: m.description, path: "/learn" });
  html += `
  <div class="flex max-w-screen-2xl mx-auto">

    <!-- learn:sidebar (generated by scripts/site-learn.mjs) -->
${sidebar(course, lessons, null)}
    <main id="main" class="flex-1 min-w-0 px-8 py-10 max-w-4xl lx-main">
      <header class="lx-hero lx-hero-index">
        <div class="lx-hero-tag">FREE COURSE</div>
        <h1>${escapeHtml(m.heading)}</h1>
        <p class="lx-hero-lead">${escapeHtml(m.lead)}</p>
        <a class="lx-start" href="/learn/${lessons[0].slug}">Start lesson 1 →</a>
      </header>

      <div class="lx-body">
${m.bodyHtml}
      </div>

      <section class="lx-tiers" aria-labelledby="tiers">
        <h2 id="tiers">Not every lesson is for everyone</h2>
        <p>Every part and lesson carries one of four labels. A complete beginner follows the whole path in order. If you already know JavaScript, skip to <a href="/learn/node-runtime">Node.js and npm</a>; if you already build backends in TypeScript, go straight to <a href="/learn/zudo-welcome">Meet ZudoJS</a>.</p>
        <ul class="lx-tier-list">
${Object.keys(course.tiers || {})
  .map((k) => `          <li>${tierBadge(course, k)}<span>${escapeHtml(course.tiers[k].summary)}</span></li>`)
  .join("\n")}
        </ul>
      </section>

      <section class="lx-map" aria-label="Course map">
${course.parts
  .filter((part) => lessons.some((l) => l.partId === part.id))
  .map(
    (part, pi) => `        <div class="lx-map-part">
          <p class="lx-map-kicker">PART ${pi + 1} ${tierBadge(course, part.tier || "foundation")}</p>
          <h2 id="${part.id}">${escapeHtml(part.title)}</h2>
          <p class="lx-map-lead">${escapeHtml(part.summary)}</p>
          <ol class="lx-map-list">
${lessons
  .filter((l) => l.partId === part.id)
  .map(
    (l) => `            <li><a href="/learn/${l.slug}" data-lesson="${l.slug}"><span class="lx-map-num">${l.number}</span><span class="lx-map-text"><strong>${escapeHtml(l.meta.title)}</strong><span>${escapeHtml(l.meta.description)}</span></span><span class="lx-map-min">${l.tier !== (part.tier || "foundation") ? tierBadge(course, l.tier, " lx-tier-sm") : ""}${escapeHtml(l.meta.minutes || "15")} min</span></a></li>`,
  )
  .join("\n")}
          </ol>
        </div>`,
  )
  .join("\n")}
      </section>
    </main>

    <aside class="doc-toc" aria-label="On this page">
      <div class="p-4 text-xs font-bold uppercase text-black/60 tracking-wider">On this page</div>
      <a href="#tiers" class="toc-link">Where to start</a>
${course.parts.filter((p) => lessons.some((l) => l.partId === p.id)).map((p) => `      <a href="#${p.id}" class="toc-link">${escapeHtml(p.title)}</a>`).join("\n")}
    </aside>
  </div>
`;
  return html + foot();
}
