/**
 * @zudojs/events/eventTypes
 *
 * Event type definitions and payload types.
 */

export {
  type EventId,
  type EventType,
  type EventTimestamp,
  type EventSource,
  type EventCorrelationId,
  type EventCausationId,
  type EventPayload,
  type Event,
  type EventInput,
  type EventDefinition,
  isEvent,
  createEventId,
  createEvent,
  defineEvent,
  withEventMetadata,
  createDerivedEvent,
  getEventType,
  getEventPayload,
  describeEvent,
} from "./eventDefinition.type.js";

export {
  type ObjectEventPayload,
  type PrimitiveEventPayload,
  type JsonEventPayload,
  type EventPayloadMap,
  type PayloadOf,
  type PayloadMap,
  type EventPayloadFactory,
  type EventPayloadOptions,
  isPrimitiveEventPayload,
  isObjectEventPayload,
  isJsonEventPayload,
  createEventPayload,
  createObjectEventPayload,
  createJsonEventPayload,
  cloneEventPayload,
  deepFreeze,
  stripUndefinedValues,
  mergeEventPayloads,
  staticPayload,
  definePayloadFactory,
  validateEventPayload,
  describeEventPayload,
} from "./eventPayload.type.js";

export {
  type EventTypeList,
  type EventTypePattern,
  type EventTypeOf,
  type EventUnion,
  isValidEventType,
  isValidEventTypePattern,
  normalizeEventType,
  normalizeEventTypePattern,
  tryNormalizeEventType,
  assertEventType,
  createEventType,
  createEventTypePattern,
  getEventNamespace,
  getEventAction,
  getEventTypeSegments,
  matchesEventType,
  isSameEventNamespace,
  isChildEventType,
  eventMatchesType,
  filterEventsByType,
  defineEventTypes,
  defineEventType,
} from "./eventType.type.js";
