/**
 * Integration generator for connecting frontend and backend.
 *
 * @module generators/integration
 */

import { existsSync } from "node:fs";
import { join } from "node:path";
import type { ProjectConfiguration } from "../../types/projectConfiguration.type.js";
import { writeFileTree } from "../../utils/utils.fileSystem.js";

/**
 * Integration generation context.
 */
export interface IntegrationContext {
  readonly project: ProjectConfiguration;
  readonly projectPath: string;
  readonly backendPort?: number;
  readonly frontendPort?: number;
}

/**
 * Generates integration files between frontend and backend.
 */
export class IntegrationGenerator {
  /**
   * Generates all integration files.
   */
  async generate(context: IntegrationContext): Promise<void> {
    const files: Record<string, string> = {};

    // Environment files
    files[".env.example"] = this.generateEnvFile(context);

    // API client for frontend
    if (context.project.frontend) {
      const apiClient = this.generateApiClient(context);
      const apiPath = this.getApiClientPath(context);
      files[apiPath] = apiClient;
    }

    // CORS configuration, written next to the backend it configures. In a
    // fullstack workspace the backend lives in apps/api; writing it at the
    // workspace root left it where nothing could import it.
    files[`${this.getBackendPath(context)}config/cors.ts`] =
      this.generateCorsConfig(context);

    // Development proxy configuration (belongs to the frontend app). The
    // frontend adapter has already written a vite.config.ts carrying the
    // framework plugin and path aliases; overwriting it with this minimal
    // proxy-only config silently destroyed that work, so only create the
    // file when the adapter did not.
    if (
      context.project.frontend?.framework === "react" ||
      context.project.frontend?.framework === "vue"
    ) {
      const viteConfigPath = "apps/web/vite.config.ts";
      if (!existsSync(join(context.projectPath, viteConfigPath))) {
        files[viteConfigPath] = this.generateViteProxy(context);
      }
    }

    await writeFileTree(context.projectPath, files);
  }

  private generateEnvFile(context: IntegrationContext): string {
    const backendPort = context.backendPort ?? 3000;
    const frontendPort = context.frontendPort ?? 5173;

    const lines: string[] = [
      "# Backend",
      `API_URL=http://localhost:${backendPort}`,
      "",
      "# Frontend",
      // The frontend dev-server port was accepted, defaulted and then never
      // written anywhere, so nothing downstream could agree with the CORS
      // origins generated from the same value.
      `FRONTEND_PORT=${frontendPort}`,
      `VITE_API_URL=http://localhost:${backendPort}`,
      "",
      "# Database",
      "DATABASE_URL=postgresql://localhost:5432/mydb",
      "",
    ];

    if (context.project.frontend?.framework === "next") {
      lines.push("# Next.js");
      lines.push(`NEXT_PUBLIC_API_URL=http://localhost:${backendPort}`);
      lines.push("");
    }

    return lines.join("\n");
  }

  /**
   * Path prefix (relative to projectPath) of the backend application.
   *
   * Ends with a "/" when non-empty so it can be prefixed directly.
   */
  private getBackendPath(context: IntegrationContext): string {
    return context.project.type === "fullstack" ? "apps/api/" : "";
  }

  private generateApiClient(context: IntegrationContext): string {
    const backendPort = context.backendPort ?? 3000;
    const isNext = context.project.frontend?.framework === "next";
    const envVar = isNext ? "NEXT_PUBLIC_API_URL" : "VITE_API_URL";

    return `/**
 * API Client for backend communication.
 * Generated by Zudojs CLI.
 */

const API_URL = ${isNext ? `process.env.${envVar}` : `import.meta.env.${envVar}`} || "http://localhost:${backendPort}";

export interface ApiResponse<T> {
  readonly data: T;
  readonly status: number;
  readonly message?: string;
}

export interface ApiError {
  readonly status: number;
  readonly message: string;
  readonly errors?: Record<string, string[]>;
}

async function request<T>(
  path: string,
  options: RequestInit = {},
): Promise<ApiResponse<T>> {
  const response = await fetch(\`\${API_URL}\${path}\`, {
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

  if (!response.ok) {
    const error: ApiError = await response.json() as ApiError;
    throw new Error(error.message || \`HTTP \${response.status}\`);
  }

  const data = await response.json() as T;
  return { data, status: response.status };
}

export const api = {
  get: <T>(path: string) => request<T>(path),
  post: <T>(path: string, body: unknown) =>
    request<T>(path, { method: "POST", body: JSON.stringify(body) }),
  put: <T>(path: string, body: unknown) =>
    request<T>(path, { method: "PUT", body: JSON.stringify(body) }),
  patch: <T>(path: string, body: unknown) =>
    request<T>(path, { method: "PATCH", body: JSON.stringify(body) }),
  delete: <T>(path: string) =>
    request<T>(path, { method: "DELETE" }),
};
`;
  }

  private getApiClientPath(context: IntegrationContext): string {
    const framework = context.project.frontend?.framework;

    if (framework === "next") {
      return "apps/web/src/lib/api-client.ts";
    }

    if (framework === "vue" || framework === "nuxt") {
      return "apps/web/src/services/api-client.ts";
    }

    if (framework === "angular") {
      return "apps/web/src/app/services/api.service.ts";
    }

    if (framework === "svelte" || framework === "sveltekit") {
      return "apps/web/src/lib/services/api-client.ts";
    }

    if (framework === "astro") {
      return "apps/web/src/utils/api-client.ts";
    }

    if (framework === "flutter") {
      return "apps/web/lib/services/api_client.dart";
    }

    if (framework === "react-native") {
      return "apps/web/src/services/api-client.ts";
    }

    return "apps/web/src/services/api-client.ts";
  }

  private generateCorsConfig(context: IntegrationContext): string {
    const frontendPort = context.frontendPort ?? 5173;

    return `/**
 * CORS configuration for development.
 * Generated by Zudojs CLI.
 */

export const corsConfig = {
  origin: [
    "http://localhost:${frontendPort}",
    "http://127.0.0.1:${frontendPort}",
  ],
  credentials: true,
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
};
`;
  }

  private generateViteProxy(context: IntegrationContext): string {
    const backendPort = context.backendPort ?? 3000;
    const isVue = context.project.frontend?.framework === "vue";
    const pluginImport = isVue
      ? `import vue from "@vitejs/plugin-vue";`
      : `import react from "@vitejs/plugin-react";`;
    const pluginCall = isVue ? "vue()" : "react()";

    return `import { defineConfig } from "vite";
${pluginImport}

export default defineConfig({
  plugins: [${pluginCall}],
  server: {
    proxy: {
      "/api": {
        target: "http://localhost:${backendPort}",
        changeOrigin: true,
      },
    },
  },
});
`;
  }
}
