/**
 * Canonical error codes provided by the Zudojs core.
 *
 * Feature-specific packages should define their own error codes
 * rather than adding every possible application error here.
 */
export const ErrorCode = {
  // General
  UNKNOWN_ERROR: "CORE_UNKNOWN_ERROR",
  INTERNAL_ERROR: "CORE_INTERNAL_ERROR",
  INVALID_ARGUMENT: "CORE_INVALID_ARGUMENT",
  INVALID_STATE: "CORE_INVALID_STATE",
  OPERATION_FAILED: "CORE_OPERATION_FAILED",
  NOT_IMPLEMENTED: "CORE_NOT_IMPLEMENTED",

  // Application lifecycle
  APPLICATION_NOT_INITIALIZED: "CORE_APPLICATION_NOT_INITIALIZED",
  APPLICATION_ALREADY_INITIALIZED: "CORE_APPLICATION_ALREADY_INITIALIZED",
  APPLICATION_ALREADY_RUNNING: "CORE_APPLICATION_ALREADY_RUNNING",
  APPLICATION_NOT_RUNNING: "CORE_APPLICATION_NOT_RUNNING",
  APPLICATION_START_FAILED: "CORE_APPLICATION_START_FAILED",
  APPLICATION_STOP_FAILED: "CORE_APPLICATION_STOP_FAILED",

  // Dependency Injection
  PROVIDER_NOT_FOUND: "CORE_PROVIDER_NOT_FOUND",
  PROVIDER_ALREADY_REGISTERED: "CORE_PROVIDER_ALREADY_REGISTERED",
  INVALID_PROVIDER: "CORE_INVALID_PROVIDER",
  DEPENDENCY_RESOLUTION_FAILED: "CORE_DEPENDENCY_RESOLUTION_FAILED",

  // Configuration
  CONFIGURATION_NOT_FOUND: "CORE_CONFIGURATION_NOT_FOUND",
  CONFIGURATION_INVALID: "CORE_CONFIGURATION_INVALID",
  CONFIGURATION_INVALID_TYPE: "CORE_CONFIGURATION_INVALID_TYPE",
  CONFIGURATION_SOURCE_FAILED: "CORE_CONFIGURATION_SOURCE_FAILED",
  CONFIGURATION_LOAD_FAILED: "CORE_CONFIGURATION_LOAD_FAILED",
  CONFIGURATION_REQUIRED: "CORE_CONFIGURATION_REQUIRED",
  CONFIGURATION_CONFLICT: "CORE_CONFIGURATION_CONFLICT",

  // Context
  EXECUTION_CONTEXT_NOT_FOUND: "CORE_EXECUTION_CONTEXT_NOT_FOUND",
  INVALID_EXECUTION_CONTEXT: "CORE_INVALID_EXECUTION_CONTEXT",
  CONTEXT_VALUE_NOT_FOUND: "CORE_CONTEXT_VALUE_NOT_FOUND",

  // Modules
  MODULE_NOT_FOUND: "CORE_MODULE_NOT_FOUND",
  MODULE_ALREADY_REGISTERED: "CORE_MODULE_ALREADY_REGISTERED",
  MODULE_INITIALIZATION_FAILED: "CORE_MODULE_INITIALIZATION_FAILED",

  // Adapters
  ADAPTER_NOT_FOUND: "CORE_ADAPTER_NOT_FOUND",
  ADAPTER_ALREADY_REGISTERED: "CORE_ADAPTER_ALREADY_REGISTERED",
  ADAPTER_INITIALIZATION_FAILED: "CORE_ADAPTER_INITIALIZATION_FAILED",
  ADAPTER_START_FAILED: "CORE_ADAPTER_START_FAILED",
  ADAPTER_STOP_FAILED: "CORE_ADAPTER_STOP_FAILED",

  // Module lifecycle
  MODULE_INVALID_DEFINITION: "CORE_MODULE_INVALID_DEFINITION",
  MODULE_DUPLICATE: "CORE_MODULE_DUPLICATE",
  MODULE_INVALID_DEPENDENCY: "CORE_MODULE_INVALID_DEPENDENCY",
  MODULE_MISSING_DEPENDENCY: "CORE_MODULE_MISSING_DEPENDENCY",
  MODULE_CIRCULAR_DEPENDENCY: "CORE_MODULE_CIRCULAR_DEPENDENCY",
  MODULE_VERSION_MISMATCH: "CORE_MODULE_VERSION_MISMATCH",
  MODULE_LOAD_FAILED: "CORE_MODULE_LOAD_FAILED",
  MODULE_START_FAILED: "CORE_MODULE_START_FAILED",
  MODULE_STOP_FAILED: "CORE_MODULE_STOP_FAILED",
  MODULE_DESTROY_FAILED: "CORE_MODULE_DESTROY_FAILED",
  MODULE_INVALID_INSTANCE: "CORE_MODULE_INVALID_INSTANCE",
  MODULE_INVALID_STATE: "CORE_MODULE_INVALID_STATE",
  MODULE_OPERATION_IN_PROGRESS: "CORE_MODULE_OPERATION_IN_PROGRESS",
  MODULE_OPERATION_NOT_ALLOWED: "CORE_MODULE_OPERATION_NOT_ALLOWED",
  MODULE_VALIDATION_FAILED: "CORE_MODULE_VALIDATION_FAILED",

  // Runtime
  RUNTIME_FAILURE: "CORE_RUNTIME_FAILURE",
  RUNTIME_ALREADY_STARTED: "CORE_RUNTIME_ALREADY_STARTED",
  RUNTIME_ALREADY_STOPPED: "CORE_RUNTIME_ALREADY_STOPPED",
  RUNTIME_FAILED: "CORE_RUNTIME_FAILED",
  RUNTIME_INVALID_TRANSITION: "CORE_RUNTIME_INVALID_TRANSITION",
  RUNTIME_BOOTSTRAP_FAILED: "CORE_RUNTIME_BOOTSTRAP_FAILED",
  RUNTIME_BOOTSTRAP_TIMEOUT: "CORE_RUNTIME_BOOTSTRAP_TIMEOUT",
  RUNTIME_SHUTDOWN_FAILED: "CORE_RUNTIME_SHUTDOWN_FAILED",
  RUNTIME_SHUTDOWN_TIMEOUT: "CORE_RUNTIME_SHUTDOWN_TIMEOUT",
  RUNTIME_OPERATION_TIMEOUT: "CORE_RUNTIME_OPERATION_TIMEOUT",
  RUNTIME_INVALID_CONFIGURATION: "CORE_RUNTIME_INVALID_CONFIGURATION",
  RUNTIME_MISSING_DEPENDENCY: "CORE_RUNTIME_MISSING_DEPENDENCY",
  RUNTIME_INVALID_ENVIRONMENT: "CORE_RUNTIME_INVALID_ENVIRONMENT",
  RUNTIME_NOT_READY: "CORE_RUNTIME_NOT_READY",
  RUNTIME_UNSUPPORTED_OPERATION: "CORE_RUNTIME_UNSUPPORTED_OPERATION",
  RUNTIME_OPERATION_CANCELLED: "CORE_RUNTIME_OPERATION_CANCELLED",

  // Configuration validation
  CONFIGURATION_VALIDATION_FAILED: "CORE_CONFIGURATION_VALIDATION_FAILED",
} as const;

/**
 * Union of all core Zudojs error codes.
 */
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
