/**
 * @zudojs/openapi/openApiConstants
 */

export {
  DEFAULT_OPENAPI_VERSION,
  SUPPORTED_OPENAPI_VERSIONS,
  MAX_OPERATION_ID_LENGTH,
  COMPONENT_REF_PREFIX,
  DEFAULT_MEDIA_TYPE,
  STATUS_CODE_CATEGORIES,
  RESPONSE_KEY_PATTERN,
  PATH_TEMPLATE_PARAMETER,
  DEFAULT_SERVER_URL,
  DOCUMENT_CACHE_TTL_MS,
} from "./openApiConstants.core.js";

export {
  SCHEMA_IMPLICIT_MAX_STRING_LENGTH,
  SCHEMA_IMPLICIT_MAX_ARRAY_LENGTH,
} from "./openApiConstants.schemaLimits.js";
