/**
 * Built-in Next.js template, written when `create-next-app` cannot run.
 *
 * @module adapters/frontend/fallback/framework/next
 */

import {
  DEPENDENCY_VERSION_RANGES as V,
  TYPESCRIPT_VERSION_RANGES,
} from "../../../../resolvers/dependency/dependencyVersions.constant.js";
import type { FrontendGenerationContext } from "../../frontendAdapter.type.js";
import { renderJsonFile, type FallbackFileTree } from "../fallback.helper.js";

/**
 * Renders the Next.js 16 App Router fallback project under `src/`, matching
 * `create-next-app --typescript --app --src-dir`.
 */
export function renderNextFallback(
  context: FrontendGenerationContext,
): FallbackFileTree {
  return {
    "package.json": renderJsonFile({
      name: context.project.name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: V.next,
        react: V.react,
        "react-dom": V["react-dom"],
      },
      devDependencies: {
        typescript: TYPESCRIPT_VERSION_RANGES.frontend,
        "@types/node": V["@types/node"],
        "@types/react": V["@types/react"],
        "@types/react-dom": V["@types/react-dom"],
      },
    }),
    "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`,
    "tsconfig.json": renderJsonFile({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: [
        "next-env.d.ts",
        "**/*.ts",
        "**/*.tsx",
        ".next/types/**/*.ts",
        ".next/dev/types/**/*.ts",
        "**/*.mts",
      ],
      exclude: ["node_modules"],
    }),
    "src/app/layout.tsx": `import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(context.project.name)},
  description: "Generated by Zudojs",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    "src/app/page.tsx": `export default function Home() {
  return (
    <main>
      <h1>Hello from Zudojs</h1>
    </main>
  );
}
`,
    "src/app/globals.css": `body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
}
`,
  };
}
