export {
  DEFAULT_RPC_TIMEOUT,
  MAX_RPC_PAYLOAD_SIZE,
  MAX_PENDING_REQUESTS,
  MAX_MIDDLEWARE,
  MAX_PROCEDURES,
  MAX_PROCEDURE_NAME_LENGTH,
  MAX_TIMER_DELAY,
  PROCEDURE_NAME_PATTERN,
  INTERNAL_ERROR_MESSAGE,
} from "./rpcConstants.core.js";
