/**
 * Standard error codes used across the Zudojs platform.
 *
 * Codes are intentionally stable because they may be consumed by
 * APIs, clients, logs, monitoring systems, and external integrations.
 */
export enum ErrorCode {
  UNKNOWN = "ERR_UNKNOWN",

  INTERNAL = "ERR_INTERNAL",
  NOT_IMPLEMENTED = "ERR_NOT_IMPLEMENTED",
  SERVICE_UNAVAILABLE = "ERR_SERVICE_UNAVAILABLE",

  INVALID_INPUT = "ERR_INVALID_INPUT",
  VALIDATION_FAILED = "ERR_VALIDATION_FAILED",
  INVALID_FORMAT = "ERR_INVALID_FORMAT",
  INVALID_VALUE = "ERR_INVALID_VALUE",
  MISSING_FIELD = "ERR_MISSING_FIELD",
  INVALID_FIELD = "ERR_INVALID_FIELD",

  UNAUTHORIZED = "ERR_UNAUTHORIZED",
  FORBIDDEN = "ERR_FORBIDDEN",
  ACCESS_DENIED = "ERR_ACCESS_DENIED",

  NOT_FOUND = "ERR_NOT_FOUND",
  RESOURCE_NOT_FOUND = "ERR_RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND = "ERR_ROUTE_NOT_FOUND",

  CONFLICT = "ERR_CONFLICT",
  ALREADY_EXISTS = "ERR_ALREADY_EXISTS",
  DUPLICATE = "ERR_DUPLICATE",

  RATE_LIMITED = "ERR_RATE_LIMITED",
  TOO_MANY_REQUESTS = "ERR_TOO_MANY_REQUESTS",

  TIMEOUT = "ERR_TIMEOUT",
  REQUEST_TIMEOUT = "ERR_REQUEST_TIMEOUT",

  NETWORK = "ERR_NETWORK",
  CONNECTION_FAILED = "ERR_CONNECTION_FAILED",

  DATABASE = "ERR_DATABASE",
  DATABASE_CONNECTION = "ERR_DATABASE_CONNECTION",
  DATABASE_QUERY = "ERR_DATABASE_QUERY",
  DATABASE_TRANSACTION = "ERR_DATABASE_TRANSACTION",

  CONFIGURATION = "ERR_CONFIGURATION",
  CONFIGURATION_MISSING = "ERR_CONFIGURATION_MISSING",
  CONFIGURATION_INVALID = "ERR_CONFIGURATION_INVALID",

  AUTHENTICATION = "ERR_AUTHENTICATION",
  AUTHENTICATION_FAILED = "ERR_AUTHENTICATION_FAILED",
  INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS",
  SESSION_EXPIRED = "ERR_SESSION_EXPIRED",
  TOKEN_INVALID = "ERR_TOKEN_INVALID",
  TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED",

  CRYPTO = "ERR_CRYPTO",
  CRYPTO_KEY = "ERR_CRYPTO_KEY",
  CRYPTO_HASH = "ERR_CRYPTO_HASH",
  CRYPTO_CIPHER = "ERR_CRYPTO_CIPHER",
  CRYPTO_SIGNATURE = "ERR_CRYPTO_SIGNATURE",
  CRYPTO_DERIVATION = "ERR_CRYPTO_DERIVATION",

  EXTERNAL_SERVICE = "ERR_EXTERNAL_SERVICE",
  EXTERNAL_SERVICE_TIMEOUT = "ERR_EXTERNAL_SERVICE_TIMEOUT",
  EXTERNAL_SERVICE_UNAVAILABLE = "ERR_EXTERNAL_SERVICE_UNAVAILABLE",

  FILE = "ERR_FILE",
  FILE_NOT_FOUND = "ERR_FILE_NOT_FOUND",
  FILE_READ = "ERR_FILE_READ",
  FILE_WRITE = "ERR_FILE_WRITE",
  FILE_UPLOAD = "ERR_FILE_UPLOAD",
  FILE_DOWNLOAD = "ERR_FILE_DOWNLOAD",

  PERMISSION = "ERR_PERMISSION",
  RESOURCE_LOCKED = "ERR_RESOURCE_LOCKED",

  OPERATION_FAILED = "ERR_OPERATION_FAILED",
  OPERATION_CANCELLED = "ERR_OPERATION_CANCELLED",
  PRECONDITION_FAILED = "ERR_PRECONDITION_FAILED",

  INTERNAL_ERROR = "ERR_INTERNAL_ERROR",
  SYSTEM_ERROR = "ERR_SYSTEM_ERROR",
  SYSTEM_INITIALIZATION = "ERR_SYSTEM_INITIALIZATION",
  SYSTEM_STARTUP = "ERR_SYSTEM_STARTUP",
  SYSTEM_SHUTDOWN = "ERR_SYSTEM_SHUTDOWN",
  SERVICE_ERROR = "ERR_SERVICE_ERROR",
  SERVICE_INITIALIZATION = "ERR_SERVICE_INITIALIZATION",
  SERVICE_OPERATION = "ERR_SERVICE_OPERATION",
  STORAGE = "ERR_STORAGE",
  STORAGE_READ = "ERR_STORAGE_READ",
  STORAGE_WRITE = "ERR_STORAGE_WRITE",
  STORAGE_UPLOAD = "ERR_STORAGE_UPLOAD",
  STORAGE_DOWNLOAD = "ERR_STORAGE_DOWNLOAD",
  STORAGE_DELETE = "ERR_STORAGE_DELETE",
  STORAGE_NOT_FOUND = "ERR_STORAGE_NOT_FOUND",
  DATABASE_TIMEOUT = "ERR_DATABASE_TIMEOUT",
  LOCK_TIMEOUT = "ERR_LOCK_TIMEOUT",

  // CQRS
  COMMAND_HANDLER_NOT_FOUND = "ERR_COMMAND_HANDLER_NOT_FOUND",
  QUERY_HANDLER_NOT_FOUND = "ERR_QUERY_HANDLER_NOT_FOUND",
  INVALID_COMMAND = "ERR_INVALID_COMMAND",
  INVALID_QUERY = "ERR_INVALID_QUERY",
  EVENT_HANDLER_FAILED = "ERR_EVENT_HANDLER_FAILED",
  CONFIGURATION_ERROR = "ERR_CONFIGURATION_ERROR",

  // Container
  CONTAINER_DUPLICATE_REGISTRATION = "ERR_CONTAINER_DUPLICATE_REGISTRATION",
  CONTAINER_REGISTRATION_NOT_FOUND = "ERR_CONTAINER_REGISTRATION_NOT_FOUND",
  CONTAINER_CIRCULAR_DEPENDENCY = "ERR_CONTAINER_CIRCULAR_DEPENDENCY",
  CONTAINER_PROVIDER_RESOLUTION_FAILED = "ERR_CONTAINER_PROVIDER_RESOLUTION_FAILED",
  CONTAINER_LIFECYCLE = "ERR_CONTAINER_LIFECYCLE",

  // Module
  MODULE_NOT_FOUND = "ERR_MODULE_NOT_FOUND",
  MODULE_LOAD_FAILED = "ERR_MODULE_LOAD_FAILED",
  MODULE_LIFECYCLE = "ERR_MODULE_LIFECYCLE",
  MODULE_DEPENDENCY_MISSING = "ERR_MODULE_DEPENDENCY_MISSING",

  // Runtime
  RUNTIME_BOOTSTRAP = "ERR_RUNTIME_BOOTSTRAP",
  RUNTIME_SHUTDOWN = "ERR_RUNTIME_SHUTDOWN",
  RUNTIME_STATE = "ERR_RUNTIME_STATE",
  RUNTIME_ENVIRONMENT = "ERR_RUNTIME_ENVIRONMENT",
  RUNTIME_MANAGER = "ERR_RUNTIME_MANAGER",

  // Event
  EVENT_HANDLING_FAILED = "ERR_EVENT_HANDLING_FAILED",
  EVENT_PUBLISH_FAILED = "ERR_EVENT_PUBLISH_FAILED",
  EVENT_HANDLER_NOT_FOUND = "ERR_EVENT_HANDLER_NOT_FOUND",
  EVENT_DUPLICATE_HANDLER = "ERR_EVENT_DUPLICATE_HANDLER",
  EVENT_MIDDLEWARE_FAILED = "ERR_EVENT_MIDDLEWARE_FAILED",
  EVENT_INVALID = "ERR_EVENT_INVALID",
  EVENT_TYPE_NOT_FOUND = "ERR_EVENT_TYPE_NOT_FOUND",
  EVENT_DUPLICATE_DEFINITION = "ERR_EVENT_DUPLICATE_DEFINITION",
  EVENT_DEFINITION_NOT_FOUND = "ERR_EVENT_DEFINITION_NOT_FOUND",
  EVENT_DISPATCH_ABORTED = "ERR_EVENT_DISPATCH_ABORTED",
  EVENT_EMITTER_DISPOSED = "ERR_EVENT_EMITTER_DISPOSED",
  EVENT_REGISTRY_DISPOSED = "ERR_EVENT_REGISTRY_DISPOSED",
  EVENT_BUS_DISPOSED = "ERR_EVENT_BUS_DISPOSED",
  EVENT_SUBSCRIPTION_CLOSED = "ERR_EVENT_SUBSCRIPTION_CLOSED",
  EVENT_TIMEOUT = "ERR_EVENT_TIMEOUT",
  EVENT_SERIALIZATION_FAILED = "ERR_EVENT_SERIALIZATION_FAILED",
  EVENT_DESERIALIZATION_FAILED = "ERR_EVENT_DESERIALIZATION_FAILED",

  // Message
  MESSAGE_HANDLER_NOT_FOUND = "ERR_MESSAGE_HANDLER_NOT_FOUND",
  MESSAGE_DISPATCH_FAILED = "ERR_MESSAGE_DISPATCH_FAILED",
  MESSAGE_VALIDATION_FAILED = "ERR_MESSAGE_VALIDATION_FAILED",
  MESSAGE_DUPLICATE_HANDLER = "ERR_MESSAGE_DUPLICATE_HANDLER",
  MESSAGE_TIMEOUT = "ERR_MESSAGE_TIMEOUT",
  MESSAGE_ABORTED = "ERR_MESSAGE_ABORTED",
  MESSAGE_INVALID = "ERR_MESSAGE_INVALID",
  MESSAGE_BUS_DISPOSED = "ERR_MESSAGE_BUS_DISPOSED",
  /** @deprecated Use `MESSAGE_BUS_DISPOSED`. Same value; kept for compatibility. */
  MESSAGE_BUSDisposed = "ERR_MESSAGE_BUS_DISPOSED",
  MESSAGE_SERIALIZATION_FAILED = "ERR_MESSAGE_SERIALIZATION_FAILED",
  MESSAGE_DESERIALIZATION_FAILED = "ERR_MESSAGE_DESERIALIZATION_FAILED",
  MESSAGE_HANDLER_FAILED = "ERR_MESSAGE_HANDLER_FAILED",
  MESSAGE_MIDDLEWARE_FAILED = "ERR_MESSAGE_MIDDLEWARE_FAILED",
  MESSAGE_TYPE_NOT_FOUND = "ERR_MESSAGE_TYPE_NOT_FOUND",

  // Logger
  LOGGING_FAILED = "ERR_LOGGING_FAILED",

  // Middleware
  MIDDLEWARE_EXECUTION = "ERR_MIDDLEWARE_EXECUTION",
  MIDDLEWARE_TIMEOUT = "ERR_MIDDLEWARE_TIMEOUT",

  // Provider
  PROVIDER_NOT_FOUND = "ERR_PROVIDER_NOT_FOUND",
  PROVIDER_ALREADY_REGISTERED = "ERR_PROVIDER_ALREADY_REGISTERED",

  // Adapter
  ADAPTER_NOT_FOUND = "ERR_ADAPTER_NOT_FOUND",
  ADAPTER_ALREADY_REGISTERED = "ERR_ADAPTER_ALREADY_REGISTERED",
  ADAPTER_NOT_SUPPORTED = "ERR_ADAPTER_NOT_SUPPORTED",
  ADAPTER_CAPABILITY_MISSING = "ERR_ADAPTER_CAPABILITY_MISSING",
  ADAPTER_CONNECTION_FAILED = "ERR_ADAPTER_CONNECTION_FAILED",
  ADAPTER_OPERATION_FAILED = "ERR_ADAPTER_OPERATION_FAILED",
  ADAPTER_TIMEOUT = "ERR_ADAPTER_TIMEOUT",
  ADAPTER_DISPOSE_FAILED = "ERR_ADAPTER_DISPOSE_FAILED",
  ADAPTER_INITIALIZATION_FAILED = "ERR_ADAPTER_INITIALIZATION_FAILED",
  ADAPTER_CONFIGURATION_FAILED = "ERR_ADAPTER_CONFIGURATION_FAILED",
  HTTP_ADAPTER = "ERR_HTTP_ADAPTER",

  // HTTP Router
  HTTP_ROUTER = "ERR_HTTP_ROUTER",
  HTTP_ROUTE_CONFLICT = "ERR_HTTP_ROUTE_CONFLICT",
  HTTP_INVALID_ROUTE_PATTERN = "ERR_HTTP_INVALID_ROUTE_PATTERN",
  HTTP_ROUTE_PATTERN = "ERR_HTTP_ROUTE_PATTERN",
  HTTP_DUPLICATE_ROUTE_PARAM = "ERR_HTTP_DUPLICATE_ROUTE_PARAM",

  // HTTP Server
  HTTP_SERVER = "ERR_HTTP_SERVER",
  HTTP_SERVER_INVALID_STATE = "ERR_HTTP_SERVER_INVALID_STATE",
  HTTP_SERVER_START = "ERR_HTTP_SERVER_START",
  HTTP_SERVER_STOP = "ERR_HTTP_SERVER_STOP",

  // HTTP Stream
  HTTP_STREAM = "ERR_HTTP_STREAM",

  // HTTP Response Writer
  HTTP_RESPONSE_WRITE = "ERR_HTTP_RESPONSE_WRITE",
  HTTP_RESPONSE_ALREADY_SENT = "ERR_HTTP_RESPONSE_ALREADY_SENT",
  HTTP_UNSUPPORTED_RESPONSE_BODY = "ERR_HTTP_UNSUPPORTED_RESPONSE_BODY",

  // HTTP Body
  HTTP_BODY = "ERR_HTTP_BODY",
  HTTP_BODY_LIMIT = "ERR_HTTP_BODY_LIMIT",
  HTTP_BODY_ABORTED = "ERR_HTTP_BODY_ABORTED",
  HTTP_BODY_PARSE = "ERR_HTTP_BODY_PARSE",
  HTTP_BODY_PARSER = "ERR_HTTP_BODY_PARSER",
  HTTP_UNSUPPORTED_BODY_TYPE = "ERR_HTTP_UNSUPPORTED_BODY_TYPE",
  HTTP_INVALID_CONTENT_LENGTH = "ERR_HTTP_INVALID_CONTENT_LENGTH",

  // HTTP Form Data
  HTTP_FORM_DATA = "ERR_HTTP_FORM_DATA",
  HTTP_FORM_DATA_LIMIT = "ERR_HTTP_FORM_DATA_LIMIT",
  HTTP_FORM_DATA_PARSE = "ERR_HTTP_FORM_DATA_PARSE",

  // HTTP Multipart
  HTTP_MULTIPART = "ERR_HTTP_MULTIPART",
  HTTP_MULTIPART_PARSE = "ERR_HTTP_MULTIPART_PARSE",
  HTTP_MULTIPART_LIMIT = "ERR_HTTP_MULTIPART_LIMIT",

  // HTTP Request Body
  HTTP_REQUEST_BODY_TOO_LARGE = "ERR_HTTP_REQUEST_BODY_TOO_LARGE",

  // Execution Context
  EXECUTION_CONTEXT_NOT_FOUND = "ERR_EXECUTION_CONTEXT_NOT_FOUND",

  // Queue
  QUEUE_ERROR = "ERR_QUEUE_ERROR",
  QUEUE_CONNECTION = "ERR_QUEUE_CONNECTION",
  QUEUE_NOT_FOUND = "ERR_QUEUE_NOT_FOUND",
  QUEUE_CLOSED = "ERR_QUEUE_CLOSED",
  QUEUE_DISPOSED = "ERR_QUEUE_DISPOSED",

  // Job
  JOB_ERROR = "ERR_JOB_ERROR",
  JOB_NOT_FOUND = "ERR_JOB_NOT_FOUND",
  JOB_TIMEOUT = "ERR_JOB_TIMEOUT",
  JOB_CANCELLED = "ERR_JOB_CANCELLED",
  JOB_SERIALIZATION = "ERR_JOB_SERIALIZATION",
  JOB_DESERIALIZATION = "ERR_JOB_DESERIALIZATION",
  JOB_PROCESSING = "ERR_JOB_PROCESSING",
  JOB_DUPLICATE = "ERR_JOB_DUPLICATE",
  JOB_MAX_ATTEMPTS = "ERR_JOB_MAX_ATTEMPTS",
  JOB_STALLED = "ERR_JOB_STALLED",

  // Worker
  WORKER_ERROR = "ERR_WORKER_ERROR",
  WORKER_NOT_FOUND = "ERR_WORKER_NOT_FOUND",
  WORKER_LIFECYCLE = "ERR_WORKER_LIFECYCLE",

  // Serialization
  SERIALIZATION = "ERR_SERIALIZATION",
  SERIALIZATION_FAILED = "ERR_SERIALIZATION_FAILED",
  DESERIALIZATION_FAILED = "ERR_DESERIALIZATION_FAILED",
  UNSUPPORTED_FORMAT = "ERR_UNSUPPORTED_FORMAT",
  SERIALIZER_NOT_FOUND = "ERR_SERIALIZER_NOT_FOUND",
  CIRCULAR_REFERENCE = "ERR_CIRCULAR_REFERENCE",
  MAX_DEPTH_EXCEEDED = "ERR_MAX_DEPTH_EXCEEDED",
  PAYLOAD_TOO_LARGE = "ERR_PAYLOAD_TOO_LARGE",
  INVALID_SERIALIZED_DATA = "ERR_INVALID_SERIALIZED_DATA",
  TRANSFORMER_ERROR = "ERR_TRANSFORMER_ERROR",
  TRANSFORMER_NOT_FOUND = "ERR_TRANSFORMER_NOT_FOUND",

  // Schema
  SCHEMA_VALIDATION = "ERR_SCHEMA_VALIDATION",
  SCHEMA_INVALID_TYPE = "ERR_SCHEMA_INVALID_TYPE",
  SCHEMA_INVALID_LITERAL = "ERR_SCHEMA_INVALID_LITERAL",
  SCHEMA_INVALID_ENUM = "ERR_SCHEMA_INVALID_ENUM",
  SCHEMA_INVALID_UNION = "ERR_SCHEMA_INVALID_UNION",
  SCHEMA_INVALID_STRING = "ERR_SCHEMA_INVALID_STRING",
  SCHEMA_INVALID_FORMAT = "ERR_SCHEMA_INVALID_FORMAT",
  SCHEMA_INVALID_NUMBER = "ERR_SCHEMA_INVALID_NUMBER",
  SCHEMA_TOO_SMALL = "ERR_SCHEMA_TOO_SMALL",
  SCHEMA_TOO_LARGE = "ERR_SCHEMA_TOO_LARGE",
  SCHEMA_INVALID_LENGTH = "ERR_SCHEMA_INVALID_LENGTH",
  SCHEMA_INVALID_KEY = "ERR_SCHEMA_INVALID_KEY",
  SCHEMA_INVALID_ELEMENT = "ERR_SCHEMA_INVALID_ELEMENT",
  SCHEMA_UNKNOWN_KEY = "ERR_SCHEMA_UNKNOWN_KEY",
  SCHEMA_CIRCULAR_REFERENCE = "ERR_SCHEMA_CIRCULAR_REFERENCE",
  SCHEMA_MAX_DEPTH_EXCEEDED = "ERR_SCHEMA_MAX_DEPTH_EXCEEDED",
  SCHEMA_CUSTOM = "ERR_SCHEMA_CUSTOM",
  SCHEMA_PREPROCESS_FAILED = "ERR_SCHEMA_PREPROCESS_FAILED",
  SCHEMA_TRANSFORM_FAILED = "ERR_SCHEMA_TRANSFORM_FAILED",
  SCHEMA_REFINE_FAILED = "ERR_SCHEMA_REFINE_FAILED",
  SCHEMA_COERCION_FAILED = "ERR_SCHEMA_COERCION_FAILED",

  // Lifecycle
  LIFECYCLE_STATE = "ERR_LIFECYCLE_STATE",
  LIFECYCLE_TIMEOUT = "ERR_LIFECYCLE_TIMEOUT",
  LIFECYCLE_DEPENDENCY = "ERR_LIFECYCLE_DEPENDENCY",
  LIFECYCLE_COMPONENT = "ERR_LIFECYCLE_COMPONENT",
  LIFECYCLE_START = "ERR_LIFECYCLE_START",
  LIFECYCLE_STOP = "ERR_LIFECYCLE_STOP",
  LIFECYCLE_ROLLBACK = "ERR_LIFECYCLE_ROLLBACK",
  LIFECYCLE_DISPOSED = "ERR_LIFECYCLE_DISPOSED",

  // API
  API_ERROR = "ERR_API_ERROR",
  API_VALIDATION = "ERR_API_VALIDATION",
  API_AUTHENTICATION = "ERR_API_AUTHENTICATION",
  API_AUTHORIZATION = "ERR_API_AUTHORIZATION",
  API_NOT_FOUND = "ERR_API_NOT_FOUND",
  API_CONFLICT = "ERR_API_CONFLICT",
  API_RATE_LIMIT = "ERR_API_RATE_LIMIT",
  API_TIMEOUT = "ERR_API_TIMEOUT",
  API_UNAVAILABLE = "ERR_API_UNAVAILABLE",
  API_INTERNAL = "ERR_API_INTERNAL",
  API_VERSION = "ERR_API_VERSION",
  API_OPERATION_NOT_FOUND = "ERR_API_OPERATION_NOT_FOUND",
  API_DUPLICATE_OPERATION = "ERR_API_DUPLICATE_OPERATION",
  API_IDEMPOTENCY = "ERR_API_IDEMPOTENCY",

  // RPC
  RPC_ERROR = "ERR_RPC_ERROR",
  RPC_PROCEDURE_NOT_FOUND = "ERR_RPC_PROCEDURE_NOT_FOUND",
  RPC_INVALID_REQUEST = "ERR_RPC_INVALID_REQUEST",
  RPC_VALIDATION_ERROR = "ERR_RPC_VALIDATION_ERROR",
  RPC_UNAUTHORIZED = "ERR_RPC_UNAUTHORIZED",
  RPC_FORBIDDEN = "ERR_RPC_FORBIDDEN",
  RPC_TIMEOUT = "ERR_RPC_TIMEOUT",
  RPC_CANCELLED = "ERR_RPC_CANCELLED",
  RPC_INTERNAL_ERROR = "ERR_RPC_INTERNAL_ERROR",
  RPC_TRANSPORT_ERROR = "ERR_RPC_TRANSPORT_ERROR",
  RPC_SERIALIZATION_ERROR = "ERR_RPC_SERIALIZATION_ERROR",
  RPC_DESERIALIZATION_ERROR = "ERR_RPC_DESERIALIZATION_ERROR",
  RPC_UNAVAILABLE = "ERR_RPC_UNAVAILABLE",
  RPC_RATE_LIMITED = "ERR_RPC_RATE_LIMITED",
  RPC_DEADLINE_EXCEEDED = "ERR_RPC_DEADLINE_EXCEEDED",
  RPC_DUPLICATE_PROCEDURE = "ERR_RPC_DUPLICATE_PROCEDURE",

  // Feature Flags
  FEATURE_FLAG_NOT_FOUND = "ERR_FEATURE_FLAG_NOT_FOUND",
  FEATURE_FLAG_PROVIDER = "ERR_FEATURE_FLAG_PROVIDER",
  FEATURE_FLAG_EVALUATION = "ERR_FEATURE_FLAG_EVALUATION",
  FEATURE_FLAG_RULE = "ERR_FEATURE_FLAG_RULE",
  FEATURE_FLAG_DEPENDENCY = "ERR_FEATURE_FLAG_DEPENDENCY",
  FEATURE_FLAG_CONFIGURATION = "ERR_FEATURE_FLAG_CONFIGURATION",
  FEATURE_FLAG_TYPE = "ERR_FEATURE_FLAG_TYPE",

  // Scheduler
  SCHEDULER_ERROR = "ERR_SCHEDULER_ERROR",
  SCHEDULER_NOT_STARTED = "ERR_SCHEDULER_NOT_STARTED",
  SCHEDULER_ALREADY_STARTED = "ERR_SCHEDULER_ALREADY_STARTED",
  SCHEDULER_STOPPED = "ERR_SCHEDULER_STOPPED",
  SCHEDULER_JOB_NOT_FOUND = "ERR_SCHEDULER_JOB_NOT_FOUND",
  SCHEDULER_JOB_ALREADY_EXISTS = "ERR_SCHEDULER_JOB_ALREADY_EXISTS",
  INVALID_JOB = "ERR_INVALID_JOB",
  SCHEDULE_NOT_FOUND = "ERR_SCHEDULE_NOT_FOUND",
  SCHEDULE_ALREADY_EXISTS = "ERR_SCHEDULE_ALREADY_EXISTS",
  INVALID_SCHEDULE = "ERR_INVALID_SCHEDULE",
  CRON_PARSE_ERROR = "ERR_CRON_PARSE_ERROR",
  INVALID_DURATION = "ERR_INVALID_DURATION",
  SCHEDULER_JOB_EXECUTION_ERROR = "ERR_SCHEDULER_JOB_EXECUTION_ERROR",
  SCHEDULER_JOB_TIMEOUT = "ERR_SCHEDULER_JOB_TIMEOUT",
  SCHEDULER_JOB_CANCELLED = "ERR_SCHEDULER_JOB_CANCELLED",
  SCHEDULER_STORE_ERROR = "ERR_SCHEDULER_STORE_ERROR",
  SCHEDULER_LOCK_ERROR = "ERR_SCHEDULER_LOCK_ERROR",

  // OpenAPI
  OPENAPI_ERROR = "ERR_OPENAPI_ERROR",
  OPENAPI_VALIDATION = "ERR_OPENAPI_VALIDATION",
  OPENAPI_DOCUMENT = "ERR_OPENAPI_DOCUMENT",
  OPENAPI_COMPONENT = "ERR_OPENAPI_COMPONENT",
  OPENAPI_COMPONENT_CONFLICT = "ERR_OPENAPI_COMPONENT_CONFLICT",
  OPENAPI_REFERENCE = "ERR_OPENAPI_REFERENCE",
  OPENAPI_ROUTE = "ERR_OPENAPI_ROUTE",
  OPENAPI_SCHEMA = "ERR_OPENAPI_SCHEMA",
  OPENAPI_SERIALIZATION = "ERR_OPENAPI_SERIALIZATION",
  OPENAPI_VERSION = "ERR_OPENAPI_VERSION",
  OPENAPI_OPERATION = "ERR_OPENAPI_OPERATION",

  // Plugin
  PLUGIN_ERROR = "ERR_PLUGIN_ERROR",
  PLUGIN_REGISTRATION = "ERR_PLUGIN_REGISTRATION",
  PLUGIN_ALREADY_REGISTERED = "ERR_PLUGIN_ALREADY_REGISTERED",
  PLUGIN_NOT_FOUND = "ERR_PLUGIN_NOT_FOUND",
  PLUGIN_DEPENDENCY = "ERR_PLUGIN_DEPENDENCY",
  PLUGIN_DEPENDENCY_CYCLE = "ERR_PLUGIN_DEPENDENCY_CYCLE",
  PLUGIN_INITIALIZATION = "ERR_PLUGIN_INITIALIZATION",
  PLUGIN_START = "ERR_PLUGIN_START",
  PLUGIN_STOP = "ERR_PLUGIN_STOP",
  PLUGIN_DISPOSE = "ERR_PLUGIN_DISPOSE",
  PLUGIN_TIMEOUT = "ERR_PLUGIN_TIMEOUT",
  PLUGIN_STATE = "ERR_PLUGIN_STATE",

  // Documentation
  DOCUMENTATION_ERROR = "ERR_DOCUMENTATION_ERROR",
  DOCUMENT_PARSE = "ERR_DOCUMENT_PARSE",
  DOCUMENT_VALIDATION = "ERR_DOCUMENT_VALIDATION",
  DOCUMENT_DUPLICATE = "ERR_DOCUMENT_DUPLICATE",
  DOCUMENT_NOT_FOUND = "ERR_DOCUMENT_NOT_FOUND",
  DOCUMENT_LINK_BROKEN = "ERR_DOCUMENT_LINK_BROKEN",
  DOCUMENT_FRONTMATTER_INVALID = "ERR_DOCUMENT_FRONTMATTER_INVALID",
  DOCUMENT_NAVIGATION_INVALID = "ERR_DOCUMENT_NAVIGATION_INVALID",
  DOCUMENT_EXAMPLE_INVALID = "ERR_DOCUMENT_EXAMPLE_INVALID",
  DOCUMENT_GENERATION = "ERR_DOCUMENT_GENERATION",
  DOCUMENT_VERSION = "ERR_DOCUMENT_VERSION",

  // Cache
  CACHE = "ERR_CACHE",

  // Database (additional)
  DATABASE_MIGRATION = "ERR_DATABASE_MIGRATION",

  // Runtime (generic)
  RUNTIME = "ERR_RUNTIME",

  // HTTP status errors (client 4xx)
  HTTP_BAD_REQUEST = "ERR_HTTP_BAD_REQUEST",
  HTTP_UNAUTHORIZED = "ERR_HTTP_UNAUTHORIZED",
  HTTP_PAYMENT_REQUIRED = "ERR_HTTP_PAYMENT_REQUIRED",
  HTTP_FORBIDDEN = "ERR_HTTP_FORBIDDEN",
  HTTP_NOT_FOUND = "ERR_HTTP_NOT_FOUND",
  HTTP_METHOD_NOT_ALLOWED = "ERR_HTTP_METHOD_NOT_ALLOWED",
  HTTP_NOT_ACCEPTABLE = "ERR_HTTP_NOT_ACCEPTABLE",
  HTTP_PROXY_AUTHENTICATION_REQUIRED = "ERR_HTTP_PROXY_AUTHENTICATION_REQUIRED",
  HTTP_REQUEST_TIMEOUT = "ERR_HTTP_REQUEST_TIMEOUT",
  HTTP_CONFLICT = "ERR_HTTP_CONFLICT",
  HTTP_GONE = "ERR_HTTP_GONE",
  HTTP_LENGTH_REQUIRED = "ERR_HTTP_LENGTH_REQUIRED",
  HTTP_PRECONDITION_FAILED = "ERR_HTTP_PRECONDITION_FAILED",
  HTTP_PAYLOAD_TOO_LARGE = "ERR_HTTP_PAYLOAD_TOO_LARGE",
  HTTP_URI_TOO_LONG = "ERR_HTTP_URI_TOO_LONG",
  HTTP_UNSUPPORTED_MEDIA_TYPE = "ERR_HTTP_UNSUPPORTED_MEDIA_TYPE",
  HTTP_RANGE_NOT_SATISFIABLE = "ERR_HTTP_RANGE_NOT_SATISFIABLE",
  HTTP_EXPECTATION_FAILED = "ERR_HTTP_EXPECTATION_FAILED",
  HTTP_MISDIRECTED_REQUEST = "ERR_HTTP_MISDIRECTED_REQUEST",
  HTTP_UNPROCESSABLE_ENTITY = "ERR_HTTP_UNPROCESSABLE_ENTITY",
  HTTP_LOCKED = "ERR_HTTP_LOCKED",
  HTTP_FAILED_DEPENDENCY = "ERR_HTTP_FAILED_DEPENDENCY",
  HTTP_TOO_EARLY = "ERR_HTTP_TOO_EARLY",
  HTTP_UPGRADE_REQUIRED = "ERR_HTTP_UPGRADE_REQUIRED",
  HTTP_PRECONDITION_REQUIRED = "ERR_HTTP_PRECONDITION_REQUIRED",
  HTTP_TOO_MANY_REQUESTS = "ERR_HTTP_TOO_MANY_REQUESTS",
  HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = "ERR_HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE",
  HTTP_UNAVAILABLE_FOR_LEGAL_REASONS = "ERR_HTTP_UNAVAILABLE_FOR_LEGAL_REASONS",
  HTTP_REQUEST_ABORTED = "ERR_HTTP_REQUEST_ABORTED",

  // HTTP status errors (server 5xx)
  HTTP_INTERNAL_SERVER_ERROR = "ERR_HTTP_INTERNAL_SERVER_ERROR",
  HTTP_NOT_IMPLEMENTED = "ERR_HTTP_NOT_IMPLEMENTED",
  HTTP_BAD_GATEWAY = "ERR_HTTP_BAD_GATEWAY",
  HTTP_SERVICE_UNAVAILABLE = "ERR_HTTP_SERVICE_UNAVAILABLE",
  HTTP_GATEWAY_TIMEOUT = "ERR_HTTP_GATEWAY_TIMEOUT",
  HTTP_VERSION_NOT_SUPPORTED = "ERR_HTTP_VERSION_NOT_SUPPORTED",
  HTTP_INSUFFICIENT_STORAGE = "ERR_HTTP_INSUFFICIENT_STORAGE",
  HTTP_LOOP_DETECTED = "ERR_HTTP_LOOP_DETECTED",
  HTTP_NETWORK_AUTHENTICATION_REQUIRED = "ERR_HTTP_NETWORK_AUTHENTICATION_REQUIRED",

  // HTTP client (outbound requests)
  HTTP_CLIENT = "ERR_HTTP_CLIENT",
  HTTP_CLIENT_TIMEOUT = "ERR_HTTP_CLIENT_TIMEOUT",
  HTTP_CLIENT_ABORTED = "ERR_HTTP_CLIENT_ABORTED",
  HTTP_CLIENT_NETWORK = "ERR_HTTP_CLIENT_NETWORK",
  HTTP_CLIENT_REQUEST_BODY_TIMEOUT = "ERR_HTTP_CLIENT_REQUEST_BODY_TIMEOUT",
  HTTP_CLIENT_UNSUPPORTED_PROTOCOL = "ERR_HTTP_CLIENT_UNSUPPORTED_PROTOCOL",
  HTTP_CLIENT_INVALID_HEADER = "ERR_HTTP_CLIENT_INVALID_HEADER",
  HTTP_CLIENT_INVALID_CONTENT_TYPE = "ERR_HTTP_CLIENT_INVALID_CONTENT_TYPE",
}

/** Precomputed set of every error code value. */
const ERROR_CODE_VALUES: ReadonlySet<string> = new Set<string>(
  Object.values(ErrorCode),
);

/**
 * Determines whether a value is a valid Zudojs error code.
 */
export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === "string" && ERROR_CODE_VALUES.has(value);
}

/**
 * Converts an unknown value into a valid error code.
 */
export function normalizeErrorCode(value: unknown): ErrorCode {
  if (isErrorCode(value)) {
    return value;
  }

  return ErrorCode.UNKNOWN;
}
