#!/usr/bin/env node
/**
 * Builds and verifies the Learn course (/learn).
 *
 *   pnpm site:learn                  build site/learn/*.html from site-src/learn
 *   pnpm site:learn:check            build, then run every example in Node (npm packages,
 *                                    tsx, tsc) and in the browser terminal, and check the
 *                                    terminal's Node-style formatter against util.inspect
 *   node scripts/site-learn.mjs --node|--browser|--inspect|--quiz|--links [--only <slug>[,<slug>…]]
 *   node scripts/site-learn.mjs --fill --only <slug>   write real Node output into empty <output>s
 *
 * Lesson tests live in site-src/learn/quiz/<slug>.html (see scripts/learn/quiz.mjs);
 * --quiz checks them in Node and in the browser terminal (--check includes it).
 *
 * Lesson sources live in site-src/learn (see scripts/learn/source.mjs for the tags).
 * The generated pages are committed, because Vercel never runs this script.
 * After adding a lesson, run `pnpm site:seo` and `pnpm site:llms` so the new page
 * gets its SEO tags, sitemap entry and Markdown mirror. Rebuilding keeps the SEO
 * block a page already has, so a plain rebuild does not undo site:seo.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "node:util";

import { checkBrowser } from "./learn/check-browser.mjs";
import { checkNode } from "./learn/check-node.mjs";
import { checkQuizNode } from "./learn/check-quiz.mjs";
import { quizJson, readQuizzes } from "./learn/quiz.mjs";
import { coursePage, indexPage, lessonPage } from "./learn/page.mjs";
import { headings, loadHighlighter, readCourse, renderBody } from "./learn/source.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "site", "learn");
const args = process.argv.slice(2);
if (args.includes("--help") || args.includes("-h")) {
  const doc = readFileSync(fileURLToPath(import.meta.url), "utf8").match(/\/\*\*([\s\S]*?)\*\//)[1];
  console.log(doc.replace(/^ ?\* ?/gm, "").trim());
  process.exit(0);
}
/* --only slug[,slug…] limits the checks (the build always covers every lesson). */
const only = args.includes("--only") ? args[args.indexOf("--only") + 1].split(",") : null;
const wantAll = args.includes("--check");

/* Same shape as extractExamples in source.mjs: an example or file, then its optional <output>. */
const EXAMPLE_RE = /<(example|file)\b([^>]*)>[\s\S]*?<\/\1>(\s*<output\b([^>]*)>[\s\S]*?<\/output>)?/g;

const SEO_BLOCK = /[ \t]*<!-- seo:start -->[\s\S]*?<!-- seo:end -->/;

/* Writes a page, carrying over the SEO block site:seo filled in earlier. */
function writePage(file, html) {
  if (existsSync(file)) {
    const old = readFileSync(file, "utf8").match(SEO_BLOCK);
    if (old) html = html.replace(SEO_BLOCK, old[0]);
  }
  writeFileSync(file, html);
}

function build() {
  const { course, lessons } = readCourse(ROOT);
  const highlight = loadHighlighter(ROOT);
  const quizzes = readQuizzes(ROOT, lessons);
  mkdirSync(join(OUT, "quiz"), { recursive: true });
  for (const [slug, quiz] of quizzes) writeFileSync(join(OUT, "quiz", slug + ".json"), JSON.stringify(quizJson(quiz)));
  for (const lesson of lessons) {
    lesson.hasQuiz = quizzes.has(lesson.slug);
    const html = lessonPage({ course, lessons, lesson, bodyHtml: renderBody(lesson, highlight), toc: headings(lesson) });
    writePage(join(OUT, lesson.slug + ".html"), html);
  }
  for (const c of course.courses) {
    if (c.lessons.length) writePage(join(OUT, c.id + ".html"), coursePage({ course, c }));
  }
  course.index.bodyHtml = renderBody({ body: readFileSync(join(ROOT, "site-src", "learn", "index.html"), "utf8") }, highlight);
  writePage(join(OUT, "index.html"), indexPage({ course, lessons }));
  updateSearchIndex(course, lessons);
  const live = course.courses.filter((c) => c.lessons.length).length;
  console.log(`site/learn: ${lessons.length} lessons, ${live} course pages + index, ${quizzes.size} tests`);
  return lessons;
}

/* The header search (components.js) lists every lesson between these markers. */
function updateSearchIndex(course, lessons) {
  const file = join(ROOT, "site", "js", "components.js");
  const src = readFileSync(file, "utf8");
  const start = "    /* learn-search:start (generated by scripts/site-learn.mjs) */\n";
  const end = "    /* learn-search:end */\n";
  const a = src.indexOf(start);
  const b = src.indexOf(end);
  if (a === -1 || b === -1) throw new Error("learn-search markers missing from components.js");
  const rows = [
    ...course.courses
      .filter((c) => c.lessons.length)
      .map((c) => `    { g: 'Learn', t: ${JSON.stringify(`Course: ${c.title}`)}, p: '/learn/${c.id}', e: ${JSON.stringify(c.summary)} },\n`),
    ...lessons.map(
      (l) => `    { g: 'Learn', t: ${JSON.stringify(`${l.meta.title} (${l.course.title} ${l.number})`)}, p: '/learn/${l.slug}', e: ${JSON.stringify(l.meta.description)} },\n`,
    ),
  ].join("");
  writeFileSync(file, src.slice(0, a + start.length) + rows + src.slice(b));
}

/* The browser terminal's formatter must print exactly what Node prints. */
/* Circular structures: Node numbers them and prefixes the target with <ref *N>. */
function circular() {
  const cart = { name: "cart", items: [] };
  cart.self = cart;
  const order = { lines: {} };
  order.lines.parent = order;
  order.all = [order];
  const a = {};
  const b = { a };
  a.b = b;
  const c = { id: 1 };
  c.me = c;
  const d = { id: 2 };
  d.me = d;
  return [cart, [cart], order, a, { c, d }];
}

function checkInspect() {
  const src = readFileSync(join(ROOT, "site", "js", "playground.js"), "utf8");
  const body = src.slice(src.indexOf("/* node-inspect:start"), src.indexOf("/* node-inspect:end */"));
  const { formatArgs } = new Function(body + "\nreturn { formatArgs };")();
  class Task {
    constructor(id, title) {
      this.id = id;
      this.title = title;
      this.done = false;
    }
  }
  const cases = [
    ["hello"], [1, "two", 3n, true, null, undefined], [-0], [NaN, Infinity], [{}], [[]], [{ a: 1, b: "x" }],
    [[1, 2, 3, 4, 5, 6, 7]], [Array.from({ length: 30 }, (_, i) => i * 3)], [["apple", "banana", "cherry", "date", "elderberry", "fig", "grape"]],
    [{ id: 1, title: "Write the docs for the learn section of the site", done: false, tags: ["docs", "learn"], owner: { id: 7, name: "Ada" } }],
    [new Task(1, "Buy milk")], [{ a: { b: { c: { d: 1 } } } }], [new Map([["a", 1]])], [new Set([1, 2])], [{ "my-key": 1 }],
    [{ s: "it's" }], [function named() {}], [() => {}], [class Foo {}], [new Date(0)], [/ab+c/gi], ["%s is %d", "Ada", 36],
    [Object.create(null)], [new Uint8Array([1, 2])], [Array.from({ length: 120 }, (_, i) => i)],
    [[{ id: 1, title: "Write tests", done: true }, { id: 2, title: "Ship the API", done: false }, { id: 3, title: "Celebrate", done: false }]],
    [{ [Symbol("s")]: 1 }], [{ get g() { return 1; } }], circular(), [{ a: "line one of a long text\nline two of the long text that goes on\nline three" }],
  ];
  return cases.map((c, i) => {
    const want = format(...c);
    const got = formatArgs(c);
    return { label: `inspect case ${i}`, ok: want === got, detail: want === got ? "" : `node:\n${want}\nours:\n${got}` };
  });
}

/*
 * Every /learn/<slug> link in a lesson must point at a course or a lesson in
 * course.json (a failure otherwise). Links to planned lessons that are not
 * written yet are listed as a warning, so they are fixed before release.
 */
function checkLinks(course, lessons, only) {
  const planned = new Set(["index", ...course.courses.flatMap((c) => [c.id, ...c.modules.flatMap((m) => m.lessons)])]);
  const written = new Set(["index", ...course.courses.filter((c) => c.lessons.length).map((c) => c.id), ...lessons.map((l) => l.slug)]);
  const results = [];
  const pending = new Set();
  for (const l of lessons) {
    if (only && !only.includes(l.slug)) continue;
    for (const m of l.body.matchAll(/href="\/learn\/([\w-]+)/g)) {
      if (!planned.has(m[1])) results.push({ label: `${l.slug} links to /learn/${m[1]}`, ok: false, detail: "no such course or lesson in course.json" });
      else if (!written.has(m[1])) pending.add(m[1]);
    }
  }
  if (pending.size) console.log(`links to lessons not written yet: ${[...pending].sort().join(", ")}`);
  return results.length ? results : [{ label: "links", ok: true }];
}

function report(name, results) {
  const failed = results.filter((r) => !r.ok);
  for (const r of failed) console.log(`✗ ${r.label}\n${r.detail}\n`);
  console.log(`${name}: ${results.length - failed.length}/${results.length} passed`);
  return failed.length;
}

/*
 * --fill: run the examples of the --only lessons in Node and write the real output
 * into every <output> that is still empty, and tsc's code into every empty
 * <file check="emit">. Written ones are never touched, and DOM examples (browser
 * only) are not filled.
 */
if (args.includes("--fill")) {
  if (!only) throw new Error("--fill needs --only <slug>[,<slug>…]");
  const fills = [];
  checkNode(readCourse(ROOT).lessons, { only, root: ROOT, fill: fills });
  for (const slug of only) {
    const mine = fills.filter((f) => f.slug === slug);
    if (!mine.length) continue;
    const file = join(ROOT, "site-src", "learn", slug + ".html");
    let n = -1;
    const src = readFileSync(file, "utf8").replace(EXAMPLE_RE, (m, tag, a, out) => {
      n++;
      const f = mine.find((x) => x.index === n);
      if (!f) return m;
      /* An empty <file check="emit"> gets tsc's emitted code as its body. */
      if (f.body) return m.replace(/^(<file\b[^>]*>)\s*(<\/file>)/, (all, open, close) => `${open}\n${f.text}\n${close}`);
      if (out === undefined) return m;
      return m.replace(/(<output\b[^>]*>)\s*(<\/output>)$/, (all, open, close) => `${open}\n${f.text}\n${close}`);
    });
    writeFileSync(file, src);
    console.log(`${slug}: filled ${mine.length} output${mine.length === 1 ? "" : "s"}`);
  }
}

const lessons = build();
const wantQuiz = wantAll || args.includes("--quiz");
const quizzes = new Map([...readQuizzes(ROOT, lessons)].filter(([slug]) => !only || only.includes(slug)));
let failures = 0;
if (wantAll || args.includes("--links")) {
  const { course, lessons: read } = readCourse(ROOT);
  failures += report("links to lessons", checkLinks(course, read, only));
}
if (wantAll || args.includes("--inspect")) failures += report("formatter vs util.inspect", checkInspect());
if (wantAll || args.includes("--node")) failures += report("examples in Node", checkNode(lessons, { only, root: ROOT }));
if (wantQuiz) failures += report("tests in Node", await checkQuizNode(quizzes, { lessons, root: ROOT }));
const wantBrowser = wantAll || args.includes("--browser");
if (wantBrowser || wantQuiz) {
  failures += report(
    wantBrowser ? "examples and tests in the browser terminal" : "tests in the browser terminal",
    await checkBrowser(ROOT, lessons, { only, quizzes: wantQuiz ? quizzes : null, examples: wantBrowser }),
  );
}
process.exitCode = failures ? 1 : 0;
