#!/usr/bin/env node
/**
 * Builds and verifies the Learn course (/learn).
 *
 *   pnpm site:learn                  build site/learn/*.html from site-src/learn
 *   pnpm site:learn:check            build, then run every example in Node (npm packages,
 *                                    tsx, tsc) and in the browser terminal, and check the
 *                                    terminal's Node-style formatter against util.inspect
 *   node scripts/site-learn.mjs --node|--browser|--inspect|--quiz [--only <slug>[,<slug>…]]
 *
 * Lesson tests live in site-src/learn/quiz/<slug>.html (see scripts/learn/quiz.mjs);
 * --quiz checks them in Node and in the browser terminal (--check includes it).
 *
 * Lesson sources live in site-src/learn (see scripts/learn/source.mjs for the tags).
 * The generated pages are committed, because Vercel never runs this script.
 * After adding a lesson, run `pnpm site:seo` and `pnpm site:llms` so the new page
 * gets its SEO tags, sitemap entry and Markdown mirror. Rebuilding keeps the SEO
 * block a page already has, so a plain rebuild does not undo site:seo.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "node:util";

import { checkBrowser } from "./learn/check-browser.mjs";
import { checkNode } from "./learn/check-node.mjs";
import { checkQuizNode } from "./learn/check-quiz.mjs";
import { quizJson, readQuizzes } from "./learn/quiz.mjs";
import { coursePage, indexPage, lessonPage } from "./learn/page.mjs";
import { headings, loadHighlighter, readCourse, renderBody } from "./learn/source.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "site", "learn");
const args = process.argv.slice(2);
/* --only slug[,slug…] limits the checks (the build always covers every lesson). */
const only = args.includes("--only") ? args[args.indexOf("--only") + 1].split(",") : null;
const wantAll = args.includes("--check");

const SEO_BLOCK = /[ \t]*<!-- seo:start -->[\s\S]*?<!-- seo:end -->/;

/* Writes a page, carrying over the SEO block site:seo filled in earlier. */
function writePage(file, html) {
  if (existsSync(file)) {
    const old = readFileSync(file, "utf8").match(SEO_BLOCK);
    if (old) html = html.replace(SEO_BLOCK, old[0]);
  }
  writeFileSync(file, html);
}

function build() {
  const { course, lessons } = readCourse(ROOT);
  const highlight = loadHighlighter(ROOT);
  const quizzes = readQuizzes(ROOT, lessons);
  mkdirSync(join(OUT, "quiz"), { recursive: true });
  for (const [slug, quiz] of quizzes) writeFileSync(join(OUT, "quiz", slug + ".json"), JSON.stringify(quizJson(quiz)));
  for (const lesson of lessons) {
    lesson.hasQuiz = quizzes.has(lesson.slug);
    const html = lessonPage({ course, lessons, lesson, bodyHtml: renderBody(lesson, highlight), toc: headings(lesson) });
    writePage(join(OUT, lesson.slug + ".html"), html);
  }
  for (const c of course.courses) {
    if (c.lessons.length) writePage(join(OUT, c.id + ".html"), coursePage({ course, c }));
  }
  course.index.bodyHtml = renderBody({ body: readFileSync(join(ROOT, "site-src", "learn", "index.html"), "utf8") }, highlight);
  writePage(join(OUT, "index.html"), indexPage({ course, lessons }));
  updateSearchIndex(course, lessons);
  const live = course.courses.filter((c) => c.lessons.length).length;
  console.log(`site/learn: ${lessons.length} lessons, ${live} course pages + index, ${quizzes.size} tests`);
  return lessons;
}

/* The header search (components.js) lists every lesson between these markers. */
function updateSearchIndex(course, lessons) {
  const file = join(ROOT, "site", "js", "components.js");
  const src = readFileSync(file, "utf8");
  const start = "    /* learn-search:start (generated by scripts/site-learn.mjs) */\n";
  const end = "    /* learn-search:end */\n";
  const a = src.indexOf(start);
  const b = src.indexOf(end);
  if (a === -1 || b === -1) throw new Error("learn-search markers missing from components.js");
  const rows = [
    ...course.courses
      .filter((c) => c.lessons.length)
      .map((c) => `    { g: 'Learn', t: ${JSON.stringify(`Course: ${c.title}`)}, p: '/learn/${c.id}', e: ${JSON.stringify(c.summary)} },\n`),
    ...lessons.map(
      (l) => `    { g: 'Learn', t: ${JSON.stringify(`${l.meta.title} (${l.course.title} ${l.number})`)}, p: '/learn/${l.slug}', e: ${JSON.stringify(l.meta.description)} },\n`,
    ),
  ].join("");
  writeFileSync(file, src.slice(0, a + start.length) + rows + src.slice(b));
}

/* The browser terminal's formatter must print exactly what Node prints. */
function checkInspect() {
  const src = readFileSync(join(ROOT, "site", "js", "playground.js"), "utf8");
  const body = src.slice(src.indexOf("/* node-inspect:start"), src.indexOf("/* node-inspect:end */"));
  const { formatArgs } = new Function(body + "\nreturn { formatArgs };")();
  class Task {
    constructor(id, title) {
      this.id = id;
      this.title = title;
      this.done = false;
    }
  }
  const cases = [
    ["hello"], [1, "two", 3n, true, null, undefined], [-0], [NaN, Infinity], [{}], [[]], [{ a: 1, b: "x" }],
    [[1, 2, 3, 4, 5, 6, 7]], [Array.from({ length: 30 }, (_, i) => i * 3)], [["apple", "banana", "cherry", "date", "elderberry", "fig", "grape"]],
    [{ id: 1, title: "Write the docs for the learn section of the site", done: false, tags: ["docs", "learn"], owner: { id: 7, name: "Ada" } }],
    [new Task(1, "Buy milk")], [{ a: { b: { c: { d: 1 } } } }], [new Map([["a", 1]])], [new Set([1, 2])], [{ "my-key": 1 }],
    [{ s: "it's" }], [function named() {}], [() => {}], [class Foo {}], [new Date(0)], [/ab+c/gi], ["%s is %d", "Ada", 36],
    [Object.create(null)], [new Uint8Array([1, 2])], [Array.from({ length: 120 }, (_, i) => i)],
    [[{ id: 1, title: "Write tests", done: true }, { id: 2, title: "Ship the API", done: false }, { id: 3, title: "Celebrate", done: false }]],
    [{ [Symbol("s")]: 1 }], [{ get g() { return 1; } }], [{ a: "line one of a long text\nline two of the long text that goes on\nline three" }],
  ];
  return cases.map((c, i) => {
    const want = format(...c);
    const got = formatArgs(c);
    return { label: `inspect case ${i}`, ok: want === got, detail: want === got ? "" : `node:\n${want}\nours:\n${got}` };
  });
}

function report(name, results) {
  const failed = results.filter((r) => !r.ok);
  for (const r of failed) console.log(`✗ ${r.label}\n${r.detail}\n`);
  console.log(`${name}: ${results.length - failed.length}/${results.length} passed`);
  return failed.length;
}

const lessons = build();
const wantQuiz = wantAll || args.includes("--quiz");
const quizzes = new Map([...readQuizzes(ROOT, lessons)].filter(([slug]) => !only || only.includes(slug)));
let failures = 0;
if (wantAll || args.includes("--inspect")) failures += report("formatter vs util.inspect", checkInspect());
if (wantAll || args.includes("--node")) failures += report("examples in Node", checkNode(lessons, { only, root: ROOT }));
if (wantQuiz) failures += report("tests in Node", await checkQuizNode(quizzes, { lessons, root: ROOT }));
const wantBrowser = wantAll || args.includes("--browser");
if (wantBrowser || wantQuiz) {
  failures += report(
    wantBrowser ? "examples and tests in the browser terminal" : "tests in the browser terminal",
    await checkBrowser(ROOT, lessons, { only, quizzes: wantQuiz ? quizzes : null, examples: wantBrowser }),
  );
}
process.exitCode = failures ? 1 : 0;
