#!/usr/bin/env node
/**
 * Writes src/constants/zudojsVersions.generated.ts: the current version of
 * every @zudojs/* workspace package, read from ../<name>/package.json.
 *
 * Generated projects depend on `^<version>` of each package, so a project
 * created by this CLI build never resolves a framework release older than
 * the one the CLI's templates were written against.
 *
 *   node scripts/generateZudojsVersions.mjs          write the file
 *   node scripts/generateZudojsVersions.mjs --check  exit 1 if it is stale
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const CLI_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGES_DIR = join(CLI_DIR, "..");
const TARGET = join(CLI_DIR, "src", "constants", "zudojsVersions.generated.ts");

/** Reads `{ "@zudojs/<name>": "<version>" }` from the workspace, sorted. */
export function readWorkspaceVersions(packagesDir = PACKAGES_DIR) {
  const versions = {};
  for (const entry of readdirSync(packagesDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const manifest = join(packagesDir, entry.name, "package.json");
    if (!existsSync(manifest)) continue;
    const pkg = JSON.parse(readFileSync(manifest, "utf-8"));
    if (typeof pkg.name !== "string" || !pkg.name.startsWith("@zudojs/")) continue;
    if (pkg.private === true) continue;
    if (!/^\d+\.\d+\.\d+$/.test(String(pkg.version))) {
      throw new Error(`${pkg.name} has a non-release version: ${pkg.version}`);
    }
    versions[pkg.name] = pkg.version;
  }
  return Object.fromEntries(
    Object.entries(versions).sort(([a], [b]) => a.localeCompare(b)),
  );
}

/** Renders the generated TypeScript module. */
export function renderVersionsModule(versions) {
  const body = Object.entries(versions)
    .map(([name, version]) => `  ${JSON.stringify(name)}: ${JSON.stringify(version)},`)
    .join("\n");
  return `/**
 * zudojs-cli — Versions of the @zudojs/* packages this CLI build targets.
 *
 * GENERATED by scripts/generateZudojsVersions.mjs from the package.json of
 * every workspace package.
 * Do not edit by hand; run \`node scripts/generateZudojsVersions.mjs\`.
 */

export const ZUDOJS_PACKAGE_VERSIONS: Readonly<Record<string, string>> =
  Object.freeze({
${body}
  });
`;
}

const isMain = process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];

if (isMain) {
  const rendered = renderVersionsModule(readWorkspaceVersions());
  const current = existsSync(TARGET) ? readFileSync(TARGET, "utf-8") : "";
  if (process.argv.includes("--check")) {
    if (current !== rendered) {
      console.error(`${TARGET} is stale. Run: node scripts/generateZudojsVersions.mjs`);
      process.exit(1);
    }
  } else if (current !== rendered) {
    writeFileSync(TARGET, rendered);
    console.log(`Wrote ${TARGET}`);
  }
}
